function createfigure(X1, YMatrix1,ylims)
%CREATEFIGURE1(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 28-Jan-2022 01:17:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'MarkerSize',10,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Sector Level Sweeping (64 measurements)',...
    'Color',[0 0 0]);
    %'Marker','o',...
    
set(plot1(2),'DisplayName','Beam Sweeping (\phi Only)','LineStyle','-.',...
    'Color',[0.501960784313725 0.501960784313725 0.501960784313725]);
set(plot1(3),'DisplayName','Beam Sweeping (\phi & \theta)',...
    'Marker','square',...
    'Color',[0.501960784313725 0.501960784313725 0.501960784313725]);
set(plot1(4),'DisplayName','2ACE w/ Multiresolution','Marker','+',...
    'Color',[1 0 0]);
set(plot1(5),'DisplayName','2ACE w/o Multiresolution','Marker','x',...
    'Color',[0.929411764705882 0.694117647058824 0.125490196078431]);
set(plot1(6),'DisplayName','2ACE w/ Nuclear','Marker','.',...
    'Color',[0.85,0.14,0.74]);
set(plot1(7),'DisplayName','PhaseLift','Marker','*',...
    'Color',[0.0901960784313725 0.529411764705882 0.0901960784313725]);
set(plot1(8),'DisplayName','PLOMP','Marker','+',...
    'Color',[0 0.447058823529412 0.741176470588235]);
set(plot1(9),'DisplayName','PLGAMP','Marker','diamond','Color',[0 1 1]);
set(plot1(10),'DisplayName','ACO (4(N_t + N_r) Measurements)','LineStyle','-.',...
    'Color',[0.5725    0.1412    0.1569]);

% Create ylabel
ylabel('RSS (dBm)');

% Create xlabel
xlabel('Number of Measurements');

% Create title
title({''});

ylim_ceil = ceil(max(YMatrix1,[],'all'));
ylim_floor = floor(min(YMatrix1,[],'all'));
% Uncomment the following line to preserve the Y-limits of the axes
xlim(axes1,[0 1024]);
ylim(ylims);%max(YMatrix1,[],'all'), min(YMatrix1,[],'all')
%ylim(axes1,[ylim_floor, ylim_ceil]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'GridLineStyle','--','LineWidth',1,'PlotBoxAspectRatio',...
    [1.25 1 1],'XTick',[4,36,121,225,361,529,784,1024],'XTickLabel',...
    {'4','36','121','225','361','529','784','1024'});
%'YTick',[-66 -64 -62 -60 -58 -56 -54 -52],'YTickLabel',...
%    {'-66','-64','-62','-60','-58','-56','-54','-52'}
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.331179765358315 0.126029055690074 0.553571414787855 0.321551671199646]);